services:
  db:
    image: postgres:15-alpine
    container_name: certian_db_local
    restart: always
    environment:
      POSTGRES_USER: user_certian
      POSTGRES_PASSWORD: password_certian
      POSTGRES_DB: certian_db
    ports:
      - "5432:5432"
    volumes:
      - certian_postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: certian_adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  certian_postgres_data:
